### ISSUE TITLE
QX1 Capture Success Transfer Fail Issue

### ISSUE THREAD

**Issue by abhasmaskey** [kota65535/sony_camera_remote_api#5]
Dear kota65535,

First of all thank you for the library. I have been using it to take timelapse pictures. I have solved all the issues regarding proper installation and QX1 gets triggered, captures pictures and sends to the raspberry pi correctly. 

However, I have noticed an issue. After taking 100 or so pictures, I get this error stating that the picture is taken but cannot transfer. I am unable to find an answer in the internet and proceeded to ask you if you know a solution to this.

The bash output is:

run-parts: executing /etc/network/if-up.d/upstart
run-parts: executing /etc/network/if-up.d/wpasupplicant
sudo bash /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/scripts/connect.sh DIRECT-owQ1:ILCE-QX1 fZcoxX1k wlan0
**Already connected.
Route already configured.
Initializing camera...
Camera initialization finished.
I, [2017-06-14T02:10:50.835673 #15041]  INFO -- Camera: Capturing...
I, [2017-06-14T02:10:53.247661 #15041]  INFO -- Camera: Capture finished. (2.41 sec)
I, [2017-06-14T02:10:53.490859 #15041]  INFO -- Camera: Transferring pict20140107_193550_0.JPG...
E, [2017-06-14T02:10:53.503639 #15041] ERROR -- Retrying: Errno::ECONNREFUSED: Connection refused - Connection refused - connect(2) for "0.0.0.0" port 8080 (0.0.0.0:8080)
E, [2017-06-14T02:10:53.504575 #15041] ERROR -- Retrying: The camera seems to be disconnected, starting retry sequence.**
E, [2017-06-14T02:10:53.505444 #15041] ERROR -- Retrying: Reconnecting...
sudo bash /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/scripts/connect.sh -r DIRECT-owQ1:ILCE-QX1 fZcoxX1k wlan0
/home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket': Connection refused - Connection refused - connect(2) for "0.0.0.0" port 8080 (0.0.0.0:8080) (Errno::ECONNREFUSED)
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/httpclient-2.8.3/lib/httpclient.rb:655:in `get_content'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:901:in `block (3 levels) in transfer_postview'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open-uri.rb:37:in `open'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:900:in `block (2 levels) in transfer_postview'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/retrying.rb:52:in `reconnect_and_retry_inner'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/retrying.rb:27:in `reconnect_and_give_up'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:899:in `block in transfer_postview'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:898:in `transfer_postview'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:158:in `capture_still'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/client/main.rb:341:in `still'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sony_camera_remote_api-0.3.1/exe/sonycam:6:in `<top (required)>'
	from /home/pi/.rbenv/versions/2.4.1/bin/sonycam:22:in `load'
	from /home/pi/.rbenv/versions/2.4.1/bin/sonycam:22:in `<main>'
  Successfully initialized wpa_supplicant
ioctl[SIOCSIWENCODEEXT]: Invalid argument
ioctl[SIOCSIWENCODEEXT]: Invalid argument
  wlan0: Trying to associate with 92:b6:86:ed:8e:3c (SSID='DIRECT-owQ1:ILCE-QX1' freq=2437 MHz)
  wlan0: Association request to the driver failed
  wlan0: Associated with 92:b6:86:ed:8e:3c
  wlan0: WPA: Key negotiation completed with 92:b6:86:ed:8e:3c [PTK=CCMP GTK=CCMP]
  wlan0: CTRL-EVENT-CONNECTED - Connection to 92:b6:86:ed:8e:3c completed [id=0 id_str=]
Connected successfully.
Route already configured.
E, [2017-06-14T02:11:09.266613 #15041] ERROR -- Retrying: Reconnected.
E, [2017-06-14T02:11:09.281952 #15041] ERROR -- Retrying: Errno::ECONNREFUSED: Connection refused - Connection refused - connect(2) for "0.0.0.0" port 8080 (0.0.0.0:8080)
E, [2017-06-14T02:11:09.282487 #15041] ERROR -- Retrying: Execution failed! Finishing retry sequence...
Reading directory /etc/network/interfaces.d
Configuring interface wlan0=wlan0 (inet)
run-parts --verbose /etc/network/if-down.d
run-parts: executing /etc/network/if-down.d/resolvconf
run-parts: executing /etc/network/if-down.d/upstart
run-parts: executing /etc/network/if-down.d/wpasupplicant
run-parts --verbose /etc/network/if-post-down.d
run-parts: executing /etc/network/if-post-down.d/avahi-daemon
run-parts: executing /etc/network/if-post-down.d/wireless-tools
run-parts: executing /etc/network/if-post-down.d/wpasupplicant
Reading local directories
Reading remote server file list
Synchronizing files
sync "./nohup.out" changed in local. uploading

After resetting the camera, everything works fine. But the thing is, I don't want to keep resetting after 100 pictures. Any clue what the problem might be?

**Comment by abhasmaskey** [comment]
Dear kota65535,
I am still having the issue. I thought the connection would break because the battery power would deplete over time making the camera harder to connect but it looks like it's not the case. I used a dummy battery and a dedicated power supply. It still showed the same issue. 

I am not sure at this point whether it's the hardware or the software that's creating the problem.
